# Generated by Django 4.2.9 on 2024-01-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='gym',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='is_busy',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='number',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start',
        ),
        migrations.AddField(
            model_name='schedule',
            name='day_of_week',
            field=models.CharField(default='Monday', max_length=10),
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(default='23:59:59'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(default='23:59:59'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='trainer_name',
            field=models.CharField(default='Unknown Trainer', max_length=255),
        ),
        migrations.AddField(
            model_name='schedule',
            name='training_name',
            field=models.CharField(default='Unknown Trainer', max_length=255),
        ),
    ]
