# Generated by Django 4.2.9 on 2024-01-13 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_schedule_options_remove_schedule_coach_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='gym',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='image',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='is_coach',
        ),
    ]
