# Generated by Django 4.2.9 on 2024-01-13 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_coach_gym_remove_coach_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='training_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.coach'),
        ),
    ]
