# Generated by Django 4.2.9 on 2024-01-13 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_schedule_training_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='trainer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.coach'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='training_name',
            field=models.CharField(default='Unknown Trainer', max_length=255),
        ),
    ]
