# Generated by Django 4.2.9 on 2024-01-13 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_schedule_trainer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='trainer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.coach'),
        ),
    ]
