# Generated by Django 4.2.9 on 2024-01-13 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_schedule_trainer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/css/img'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='trainer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.coach'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='training_name',
            field=models.CharField(default='Unknown Trainer', max_length=255, null=True),
        ),
    ]
