# Generated by Django 4.2.9 on 2024-01-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_schedule_image_alter_schedule_trainer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='image',
        ),
        migrations.AddField(
            model_name='coach',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/css/img'),
        ),
    ]
