# Generated by Django 4.2.9 on 2024-01-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_schedule_image_coach_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название абонемента')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('duration_months', models.IntegerField(verbose_name='Продолжительность (месяцев)')),
                ('visit_amount', models.IntegerField(default=0, verbose_name='Количество посещений в неделю')),
                ('app_access', models.CharField(default='Нет', max_length=10, verbose_name='Доступ к приложению с онлайн-тренировками')),
                ('features', models.TextField(blank=True, null=True, verbose_name='Особенности абонемента')),
            ],
            options={
                'verbose_name': 'Членство',
                'verbose_name_plural': 'Членства в фитнес-центре',
            },
        ),
        migrations.CreateModel(
            name='SubPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.CharField(max_length=30, verbose_name='Количество месяцев')),
                ('coefficient', models.IntegerField(verbose_name='Коэффициент')),
            ],
            options={
                'verbose_name': 'План членства',
                'verbose_name_plural': 'Планы членств',
            },
        ),
    ]
