# Generated by Django 4.2.9 on 2024-01-14 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_gymmembership_subplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='selected_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.gymmembership'),
        ),
        migrations.AddField(
            model_name='profile',
            name='selected_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.subplan'),
        ),
    ]
